import type { AgentRegistryEntry } from "../shared/types.js";

export const AGENT_REGISTRY: Record<string, AgentRegistryEntry> = {
  "TL-001": {
    id: "TL-001",
    name: "Project Manager",
    skillFile: "agents/TL-001_project_manager.md",
    team: 0,
    level: "top",
    steps: [],
    gates: [],
    autonomy: 90,
  },
  "TL-002": {
    id: "TL-002",
    name: "Showrunner",
    skillFile: "agents/TL-002_showrunner.md",
    team: 0,
    level: "top",
    steps: [],
    gates: ["g1", "g2", "g3", "g4", "g5", "gd-g2"] as any,
    autonomy: 90,
  },
  "TL-003": {
    id: "TL-003",
    name: "Producer",
    skillFile: "agents/TL-003_producer.md",
    team: 0,
    level: "top",
    steps: ["visual_look"],
    gates: [],
    autonomy: 85,
  },
  "T1-L": {
    id: "T1-L",
    name: "Creative Director",
    skillFile: "agents/T1-L_creative_director.md",
    team: 1,
    level: "leader",
    steps: ["brief", "concept"],
    gates: ["g2"],
    autonomy: 85,
  },
  "T2-L": {
    id: "T2-L",
    name: "Head Writer",
    skillFile: "agents/T2-L_head_writer.md",
    team: 2,
    level: "leader",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T2-002": {
    id: "T2-002",
    name: "AV Copywriter",
    skillFile: "agents/T2-002_av_copywriter.md",
    team: 2,
    level: "sub",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T2-006": {
    id: "T2-006",
    name: "Script Doctor",
    skillFile: "agents/T2-006_script_doctor.md",
    team: 2,
    level: "sub",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T3-L": {
    id: "T3-L",
    name: "Director of Photography",
    skillFile: "agents/T3-L_director_of_photography.md",
    team: 3,
    level: "leader",
    steps: ["visual_look", "storyboard"],
    gates: [],
    autonomy: 75,
  },
  "T3-003": {
    id: "T3-003",
    name: "Cinematic Prompt Engineer",
    skillFile: "agents/T3-003_cinematic_prompt_engineer.md",
    team: 3,
    level: "sub",
    steps: ["storyboard", "video_gen"],
    gates: [],
    autonomy: 75,
  },
  "T5-L": {
    id: "T5-L",
    name: "Sonorizador",
    skillFile: "agents/T5-L_sonorizador.md",
    team: 5,
    level: "leader",
    steps: ["audio"],
    gates: [],
    autonomy: 70,
  },
  "T6-L": {
    id: "T6-L",
    name: "Editor",
    skillFile: "agents/T6-L_editor.md",
    team: 6,
    level: "leader",
    steps: ["edit", "polish"],
    gates: [],
    autonomy: 65,
  },
  "T6-003": {
    id: "T6-003",
    name: "Delivery Master",
    skillFile: "agents/T6-003_delivery_master.md",
    team: 6,
    level: "sub",
    steps: ["delivery"],
    gates: [],
    autonomy: 90,
  },
  "T7-L": {
    id: "T7-L",
    name: "Client Service",
    skillFile: "agents/T7-L_client_service.md",
    team: 7,
    level: "leader",
    steps: ["brief", "delivery"],
    gates: [],
    autonomy: 85,
  },
  "XF-001": {
    id: "XF-001",
    name: "Cinematographic Critic",
    skillFile: "agents/XF-001_cinematographic_critic.md",
    team: 0,
    level: "cross_functional",
    steps: [],
    gates: ["g4", "g5"],
    autonomy: 100,
  },
  "T9-L": {
    id: "T9-L",
    name: "AI Model Director",
    skillFile: "agents/T9-L_ai_model_director.md",
    team: 9,
    level: "leader",
    steps: ["model_config"],
    gates: [],
    autonomy: 80,
  },
  "T9-001": {
    id: "T9-001",
    name: "Text Model Specialist",
    skillFile: "agents/T9-001_text_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-002": {
    id: "T9-002",
    name: "Image Model Specialist",
    skillFile: "agents/T9-002_image_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-003": {
    id: "T9-003",
    name: "Video Model Specialist",
    skillFile: "agents/T9-003_video_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-004": {
    id: "T9-004",
    name: "Audio Model Specialist",
    skillFile: "agents/T9-004_audio_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-005": {
    id: "T9-005",
    name: "Model Benchmarker",
    skillFile: "agents/T9-005_model_benchmarker.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },

  // ── Brand Builder Motor ──
  "BB-L": { id: "BB-L", name: "Brand Architect", skillFile: "agents/BB-L_brand_architect.md", team: 10, level: "leader", steps: ["discovery", "positioning", "brand_dna"] as any, gates: ["bb-g1", "bb-g2"] as any, autonomy: 75 },
  "BB-001": { id: "BB-001", name: "Workshop Facilitator", skillFile: "agents/BB-001_workshop_facilitator.md", team: 10, level: "sub", steps: ["discovery"] as any, gates: [], autonomy: 80 },
  "BB-002": { id: "BB-002", name: "Sociologist", skillFile: "agents/BB-002_sociologist.md", team: 10, level: "sub", steps: ["research"] as any, gates: [], autonomy: 85 },
  "BB-003": { id: "BB-003", name: "Verbal Identity Designer", skillFile: "agents/BB-003_verbal_identity_designer.md", team: 10, level: "sub", steps: ["identity"] as any, gates: [], autonomy: 70 },
  "BB-004": { id: "BB-004", name: "Visual Identity Advisor", skillFile: "agents/BB-004_visual_identity_advisor.md", team: 10, level: "sub", steps: ["identity"] as any, gates: [], autonomy: 70 },
  // ── Strategist Motor ──
  "ST-L": { id: "ST-L", name: "Chief Strategist", skillFile: "agents/ST-L_chief_strategist.md", team: 11, level: "leader", steps: ["diagnostic", "objectives", "value_prop", "briefs"] as any, gates: ["st-g1", "st-g2"] as any, autonomy: 75 },
  "ST-001": { id: "ST-001", name: "Audience Analyst", skillFile: "agents/ST-001_audience_analyst.md", team: 11, level: "sub", steps: ["audiences"] as any, gates: [], autonomy: 80 },
  "ST-002": { id: "ST-002", name: "Media Planner", skillFile: "agents/ST-002_media_planner.md", team: 11, level: "sub", steps: ["media_plan"] as any, gates: [], autonomy: 75 },
  "ST-003": { id: "ST-003", name: "Budget Allocator", skillFile: "agents/ST-003_budget_allocator.md", team: 11, level: "sub", steps: ["budget"] as any, gates: [], autonomy: 80 },
  // ── Listener Stubs ──
  "LI-001": { id: "LI-001", name: "Brand Listener", skillFile: "agents/LI-001_brand_listener.md", team: 12, level: "sub", steps: ["diagnostic"] as any, gates: [], autonomy: 90 },
  "LI-002": { id: "LI-002", name: "Culture Listener", skillFile: "agents/LI-002_culture_listener.md", team: 12, level: "sub", steps: ["research", "diagnostic", "audiences"] as any, gates: [], autonomy: 90 },
  "LI-003": { id: "LI-003", name: "Industry Listener", skillFile: "agents/LI-003_industry_listener.md", team: 12, level: "sub", steps: ["diagnostic"] as any, gates: [], autonomy: 90 },
  "LI-004": { id: "LI-004", name: "Competitive Listener", skillFile: "agents/LI-004_competitive_listener.md", team: 12, level: "sub", steps: ["research", "diagnostic", "value_prop"] as any, gates: [], autonomy: 90 },
  // ── Transversal Stubs ──
  "XA-001": { id: "XA-001", name: "Financial Agent", skillFile: "agents/XA-001_financial_agent.md", team: 13, level: "cross_functional", steps: ["budget"] as any, gates: ["st-g1"] as any, autonomy: 85 },
  "XA-002": { id: "XA-002", name: "Channel Manager", skillFile: "agents/XA-002_channel_manager.md", team: 13, level: "cross_functional", steps: ["media_plan"] as any, gates: [], autonomy: 85 },
  "XA-003": { id: "XA-003", name: "Brand Guardian", skillFile: "agents/XA-003_brand_guardian.md", team: 13, level: "cross_functional", steps: [], gates: ["bb-g2", "st-g2", "gd-g1", "gd-g2", "wr-g2", "au-g2", "wb-g2", "pp-g1"] as any, autonomy: 80 },
  "XA-004": { id: "XA-004", name: "Media Scout", skillFile: "agents/XA-004_media_scout.md", team: 13, level: "cross_functional", steps: ["media_plan"] as any, gates: [], autonomy: 85 },
  // ── Graphic Design Motor ──
  "GD-L": { id: "GD-L", name: "Art Director", skillFile: "agents/GD-L_art_director.md", team: 14, level: "leader", steps: ["brief", "design_system", "moodboard", "production"] as any, gates: ["gd-g1", "gd-g2", "gd-g3"] as any, autonomy: 75 },
  "GD-001": { id: "GD-001", name: "Design System Architect", skillFile: "agents/GD-001_design_system_architect.md", team: 14, level: "sub", steps: ["design_system"] as any, gates: [], autonomy: 80 },
  "GD-002": { id: "GD-002", name: "Graphic Composer", skillFile: "agents/GD-002_graphic_composer.md", team: 14, level: "sub", steps: ["moodboard", "production"] as any, gates: [], autonomy: 70 },
  "GD-003": { id: "GD-003", name: "Format Adapter", skillFile: "agents/GD-003_format_adapter.md", team: 14, level: "sub", steps: ["adaptation", "delivery"] as any, gates: [], autonomy: 85 },
  "GD-004": { id: "GD-004", name: "Motion Designer", skillFile: "agents/GD-004_motion_designer.md", team: 14, level: "sub", steps: ["production", "adaptation"] as any, gates: [], autonomy: 70 },
  "GD-005": { id: "GD-005", name: "Infographic Designer", skillFile: "agents/GD-005_infographic_designer.md", team: 14, level: "sub", steps: ["production"] as any, gates: [], autonomy: 75 },
  // ── Copywriter (cross-motor) ──
  "CW-001": { id: "CW-001", name: "Copywriter", skillFile: "agents/CW-001_copywriter.md", team: 15, level: "sub", steps: ["production"] as any, gates: [], autonomy: 75 },
  // ── Writers Room Motor ──
  "WR-L": { id: "WR-L", name: "Head Writer", skillFile: "agents/WR-L_head_writer.md", team: 16, level: "leader", steps: ["wr_brief", "wr_delivery"] as any, gates: ["wr-g1", "wr-g2"] as any, autonomy: 75 },
  "WR-001": { id: "WR-001", name: "Research Writer", skillFile: "agents/WR-001_research_writer.md", team: 16, level: "sub", steps: ["wr_research"] as any, gates: [], autonomy: 80 },
  "WR-002": { id: "WR-002", name: "AV Copywriter", skillFile: "agents/WR-002_av_copywriter.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 70 },
  "WR-003": { id: "WR-003", name: "Digital Copywriter", skillFile: "agents/WR-003_digital_copywriter.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 75 },
  "WR-004": { id: "WR-004", name: "SEO Content Writer", skillFile: "agents/WR-004_seo_content_writer.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 75 },
  "WR-005": { id: "WR-005", name: "Brand Copywriter", skillFile: "agents/WR-005_brand_copywriter.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 65 },
  // ── Audio Motor ──
  "AU-L": { id: "AU-L", name: "Sound Director", skillFile: "agents/AU-L_sound_director.md", team: 17, level: "leader", steps: ["au_brief", "au_delivery"] as any, gates: ["au-g1", "au-g2"] as any, autonomy: 75 },
  "AU-001": { id: "AU-001", name: "Sound Designer & SFX", skillFile: "agents/AU-001_sound_designer.md", team: 17, level: "sub", steps: ["au_sound_design"] as any, gates: [], autonomy: 75 },
  "AU-002": { id: "AU-002", name: "Music Producer", skillFile: "agents/AU-002_music_producer.md", team: 17, level: "sub", steps: ["au_production"] as any, gates: [], autonomy: 70 },
  "AU-003": { id: "AU-003", name: "Voice Director", skillFile: "agents/AU-003_voice_director.md", team: 17, level: "sub", steps: ["au_production"] as any, gates: [], autonomy: 70 },
  "AU-004": { id: "AU-004", name: "Mix Engineer", skillFile: "agents/AU-004_mix_engineer.md", team: 17, level: "sub", steps: ["au_mix_master"] as any, gates: [], autonomy: 80 },
  // ── Web Motor ──
  "WB-L": { id: "WB-L", name: "Web Director", skillFile: "agents/WB-L_web_director.md", team: 18, level: "leader", steps: ["wb_brief", "wb_delivery"] as any, gates: ["wb-g1", "wb-g2", "wb-g3"] as any, autonomy: 75 },
  "WB-001": { id: "WB-001", name: "Information Architect", skillFile: "agents/WB-001_information_architect.md", team: 18, level: "sub", steps: ["wb_architecture"] as any, gates: [], autonomy: 80 },
  "WB-002": { id: "WB-002", name: "Web Content Composer", skillFile: "agents/WB-002_web_content_composer.md", team: 18, level: "sub", steps: ["wb_content"] as any, gates: [], autonomy: 75 },
  "WB-003": { id: "WB-003", name: "SEO Specialist", skillFile: "agents/WB-003_seo_specialist.md", team: 18, level: "sub", steps: ["wb_seo"] as any, gates: [], autonomy: 80 },
  "WB-004": { id: "WB-004", name: "QA Tester", skillFile: "agents/WB-004_qa_tester.md", team: 18, level: "sub", steps: ["wb_qa"] as any, gates: [], autonomy: 85 },
  "WB-005": { id: "WB-005", name: "Build Engineer", skillFile: "agents/WB-005_build_engineer.md", team: 18, level: "sub", steps: ["wb_build"] as any, gates: [], autonomy: 80 },
  // ── Marketplace Motor (Transversal) ──
  "MK-L": { id: "MK-L", name: "Procurement Director", skillFile: "agents/MK-L_procurement_director.md", team: 19, level: "leader", steps: ["mk_request", "mk_delivery"] as any, gates: ["mk-g1", "mk-g2"] as any, autonomy: 70 },
  "MK-001": { id: "MK-001", name: "Vendor Scout", skillFile: "agents/MK-001_vendor_scout.md", team: 19, level: "sub", steps: ["mk_search", "mk_quote"] as any, gates: [], autonomy: 80 },
  "MK-002": { id: "MK-002", name: "Comparator", skillFile: "agents/MK-002_comparator.md", team: 19, level: "sub", steps: ["mk_compare"] as any, gates: [], autonomy: 85 },
  "MK-003": { id: "MK-003", name: "Contract Manager", skillFile: "agents/MK-003_contract_manager.md", team: 19, level: "sub", steps: ["mk_contract", "mk_tracking", "pp_production_tracking"] as any, gates: [], autonomy: 75 },
  // ── Print Production Motor ──
  "PP-L": { id: "PP-L", name: "Print Director", skillFile: "agents/PP-L_print_director.md", team: 20, level: "leader", steps: ["pp_brief", "pp_delivery"] as any, gates: ["pp-g1", "pp-g2"] as any, autonomy: 70 },
  "PP-001": { id: "PP-001", name: "Prepress Specialist", skillFile: "agents/PP-001_prepress_specialist.md", team: 20, level: "sub", steps: ["pp_prepress"] as any, gates: [], autonomy: 80 },
  "PP-002": { id: "PP-002", name: "Print Buyer", skillFile: "agents/PP-002_print_buyer.md", team: 20, level: "sub", steps: ["pp_vendor_request"] as any, gates: [], autonomy: 75 },
  "PP-003": { id: "PP-003", name: "Quality Inspector", skillFile: "agents/PP-003_quality_inspector.md", team: 20, level: "sub", steps: ["pp_quality_check"] as any, gates: [], autonomy: 70 },
  // ── Events Motor ──
  "EV-L": { id: "EV-L", name: "Event Director", skillFile: "agents/EV-L_event_director.md", team: 21, level: "leader", steps: ["ev_brief", "ev_concept", "ev_delivery"] as any, gates: ["ev-g1", "ev-g2", "ev-g3"] as any, autonomy: 70 },
  "EV-001": { id: "EV-001", name: "Event Planner", skillFile: "agents/EV-001_event_planner.md", team: 21, level: "sub", steps: ["ev_planning"] as any, gates: [], autonomy: 75 },
  "EV-002": { id: "EV-002", name: "Logistics Coordinator", skillFile: "agents/EV-002_logistics_coordinator.md", team: 21, level: "sub", steps: ["ev_vendor_setup"] as any, gates: [], autonomy: 70 },
  "EV-003": { id: "EV-003", name: "Content Activator", skillFile: "agents/EV-003_content_activator.md", team: 21, level: "sub", steps: ["ev_pre_event", "ev_live_event", "ev_post_event"] as any, gates: [], autonomy: 65 },
  "EV-004": { id: "EV-004", name: "Event Analyst", skillFile: "agents/EV-004_event_analyst.md", team: 21, level: "sub", steps: ["ev_post_event"] as any, gates: [], autonomy: 80 },
  "EV-005": { id: "EV-005", name: "Guest Manager", skillFile: "agents/EV-005_guest_manager.md", team: 21, level: "sub", steps: ["ev_pre_event", "ev_live_event"] as any, gates: [], autonomy: 75 },
};
