import type { AgentRegistryEntry } from "../shared/types.js";

export const AGENT_REGISTRY: Record<string, AgentRegistryEntry> = {
  "TL-001": {
    id: "TL-001",
    name: "Project Manager",
    skillFile: "agents/TL-001_project_manager.md",
    team: 0,
    level: "top",
    steps: [],
    gates: [],
    autonomy: 90,
  },
  "TL-002": {
    id: "TL-002",
    name: "Showrunner",
    skillFile: "agents/TL-002_showrunner.md",
    team: 0,
    level: "top",
    steps: [],
    gates: ["g1", "g2", "g3", "g4", "g5", "gd-g2"] as any,
    autonomy: 90,
  },
  "TL-003": {
    id: "TL-003",
    name: "Producer",
    skillFile: "agents/TL-003_producer.md",
    team: 0,
    level: "top",
    steps: ["visual_look"],
    gates: [],
    autonomy: 85,
  },
  "T1-L": {
    id: "T1-L",
    name: "Creative Director",
    skillFile: "agents/T1-L_creative_director.md",
    team: 1,
    level: "leader",
    steps: ["brief", "concept"],
    gates: ["g2"],
    autonomy: 85,
  },
  "T2-L": {
    id: "T2-L",
    name: "Head Writer",
    skillFile: "agents/T2-L_head_writer.md",
    team: 2,
    level: "leader",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T2-002": {
    id: "T2-002",
    name: "AV Copywriter",
    skillFile: "agents/T2-002_av_copywriter.md",
    team: 2,
    level: "sub",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T2-006": {
    id: "T2-006",
    name: "Script Doctor",
    skillFile: "agents/T2-006_script_doctor.md",
    team: 2,
    level: "sub",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T3-L": {
    id: "T3-L",
    name: "Director of Photography",
    skillFile: "agents/T3-L_director_of_photography.md",
    team: 3,
    level: "leader",
    steps: ["visual_look", "storyboard"],
    gates: [],
    autonomy: 75,
  },
  "T3-003": {
    id: "T3-003",
    name: "Cinematic Prompt Engineer",
    skillFile: "agents/T3-003_cinematic_prompt_engineer.md",
    team: 3,
    level: "sub",
    steps: ["storyboard", "video_gen"],
    gates: [],
    autonomy: 75,
  },
  "T5-L": {
    id: "T5-L",
    name: "Sonorizador",
    skillFile: "agents/T5-L_sonorizador.md",
    team: 5,
    level: "leader",
    steps: ["audio"],
    gates: [],
    autonomy: 70,
  },
  "T6-L": {
    id: "T6-L",
    name: "Editor",
    skillFile: "agents/T6-L_editor.md",
    team: 6,
    level: "leader",
    steps: ["edit", "polish"],
    gates: [],
    autonomy: 65,
  },
  "T6-003": {
    id: "T6-003",
    name: "Delivery Master",
    skillFile: "agents/T6-003_delivery_master.md",
    team: 6,
    level: "sub",
    steps: ["delivery"],
    gates: [],
    autonomy: 90,
  },
  "T7-L": {
    id: "T7-L",
    name: "Client Service",
    skillFile: "agents/T7-L_client_service.md",
    team: 7,
    level: "leader",
    steps: ["brief", "delivery"],
    gates: [],
    autonomy: 85,
  },
  "XF-001": {
    id: "XF-001",
    name: "Cinematographic Critic",
    skillFile: "agents/XF-001_cinematographic_critic.md",
    team: 0,
    level: "cross_functional",
    steps: [],
    gates: ["g4", "g5"],
    autonomy: 100,
  },
  "T9-L": {
    id: "T9-L",
    name: "AI Model Director",
    skillFile: "agents/T9-L_ai_model_director.md",
    team: 9,
    level: "leader",
    steps: ["model_config"],
    gates: [],
    autonomy: 80,
  },
  "T9-001": {
    id: "T9-001",
    name: "Text Model Specialist",
    skillFile: "agents/T9-001_text_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-002": {
    id: "T9-002",
    name: "Image Model Specialist",
    skillFile: "agents/T9-002_image_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-003": {
    id: "T9-003",
    name: "Video Model Specialist",
    skillFile: "agents/T9-003_video_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-004": {
    id: "T9-004",
    name: "Audio Model Specialist",
    skillFile: "agents/T9-004_audio_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-005": {
    id: "T9-005",
    name: "Model Benchmarker",
    skillFile: "agents/T9-005_model_benchmarker.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },

  // ── Brand Builder Motor ──
  "BB-L": { id: "BB-L", name: "Brand Architect", skillFile: "agents/BB-L_brand_architect.md", team: 10, level: "leader", steps: ["discovery", "positioning", "brand_dna"] as any, gates: ["bb-g1", "bb-g2"] as any, autonomy: 75 },
  "BB-001": { id: "BB-001", name: "Workshop Facilitator", skillFile: "agents/BB-001_workshop_facilitator.md", team: 10, level: "sub", steps: ["discovery"] as any, gates: [], autonomy: 80 },
  "BB-002": { id: "BB-002", name: "Sociologist", skillFile: "agents/BB-002_sociologist.md", team: 10, level: "sub", steps: ["research"] as any, gates: [], autonomy: 85 },
  "BB-003": { id: "BB-003", name: "Verbal Identity Designer", skillFile: "agents/BB-003_verbal_identity_designer.md", team: 10, level: "sub", steps: ["identity"] as any, gates: [], autonomy: 70 },
  "BB-004": { id: "BB-004", name: "Visual Identity Advisor", skillFile: "agents/BB-004_visual_identity_advisor.md", team: 10, level: "sub", steps: ["identity"] as any, gates: [], autonomy: 70 },
  // ── Strategist Motor ──
  "ST-L": { id: "ST-L", name: "Chief Strategist", skillFile: "agents/ST-L_chief_strategist.md", team: 11, level: "leader", steps: ["diagnostic", "objectives", "value_prop", "briefs"] as any, gates: ["st-g1", "st-g2"] as any, autonomy: 75 },
  "ST-001": { id: "ST-001", name: "Audience Analyst", skillFile: "agents/ST-001_audience_analyst.md", team: 11, level: "sub", steps: ["audiences"] as any, gates: [], autonomy: 80 },
  "ST-002": { id: "ST-002", name: "Media Planner", skillFile: "agents/ST-002_media_planner.md", team: 11, level: "sub", steps: ["media_plan"] as any, gates: [], autonomy: 75 },
  "ST-003": { id: "ST-003", name: "Budget Allocator", skillFile: "agents/ST-003_budget_allocator.md", team: 11, level: "sub", steps: ["budget"] as any, gates: [], autonomy: 80 },
  // ── Listener Stubs ──
  "LI-001": { id: "LI-001", name: "Brand Listener", skillFile: "agents/LI-001_brand_listener.md", team: 12, level: "sub", steps: ["diagnostic"] as any, gates: [], autonomy: 90 },
  "LI-002": { id: "LI-002", name: "Culture Listener", skillFile: "agents/LI-002_culture_listener.md", team: 12, level: "sub", steps: ["research", "diagnostic", "audiences"] as any, gates: [], autonomy: 90 },
  "LI-003": { id: "LI-003", name: "Industry Listener", skillFile: "agents/LI-003_industry_listener.md", team: 12, level: "sub", steps: ["diagnostic"] as any, gates: [], autonomy: 90 },
  "LI-004": { id: "LI-004", name: "Competitive Listener", skillFile: "agents/LI-004_competitive_listener.md", team: 12, level: "sub", steps: ["research", "diagnostic", "value_prop"] as any, gates: [], autonomy: 90 },
  // ── Transversal Stubs ──
  "XA-001": { id: "XA-001", name: "Financial Agent", skillFile: "agents/XA-001_financial_agent.md", team: 13, level: "cross_functional", steps: ["budget"] as any, gates: ["st-g1", "ad-g1"] as any, autonomy: 85 },
  "XA-002": { id: "XA-002", name: "Channel Manager", skillFile: "agents/XA-002_channel_manager.md", team: 13, level: "cross_functional", steps: ["media_plan"] as any, gates: [], autonomy: 85 },
  "BG-L": {
    id: "BG-L",
    name: "Brand Guardian Director",
    skillFile: "agents/BG-L_brand_guardian_director.md",
    team: 12,
    level: "leader",
    steps: [] as any,
    gates: ["bb-g2", "st-g2", "gd-g1", "gd-g2", "wr-g2", "au-g2", "wb-g2", "pp-g1", "ad-g2", "cm-g2", "em-g2", "sl-g2"] as any,
    autonomy: 75,
  },
  "BG-001": {
    id: "BG-001",
    name: "Verbal Validator",
    skillFile: "agents/BG-001_verbal_validator.md",
    team: 12,
    level: "sub",
    steps: [] as any,
    gates: [] as any,
    autonomy: 90,
  },
  "BG-002": {
    id: "BG-002",
    name: "Visual Validator",
    skillFile: "agents/BG-002_visual_validator.md",
    team: 12,
    level: "sub",
    steps: [] as any,
    gates: [] as any,
    autonomy: 85,
  },
  "BG-003": {
    id: "BG-003",
    name: "Manual Generator",
    skillFile: "agents/BG-003_manual_generator.md",
    team: 12,
    level: "sub",
    steps: [] as any,
    gates: [] as any,
    autonomy: 85,
  },
  "XA-004": { id: "XA-004", name: "Media Scout", skillFile: "agents/XA-004_media_scout.md", team: 13, level: "cross_functional", steps: ["media_plan"] as any, gates: [], autonomy: 85 },
  // ── Graphic Design Motor ──
  "GD-L": { id: "GD-L", name: "Art Director", skillFile: "agents/GD-L_art_director.md", team: 14, level: "leader", steps: ["brief", "design_system", "moodboard", "production"] as any, gates: ["gd-g1", "gd-g2", "gd-g3"] as any, autonomy: 75 },
  "GD-001": { id: "GD-001", name: "Design System Architect", skillFile: "agents/GD-001_design_system_architect.md", team: 14, level: "sub", steps: ["design_system"] as any, gates: [], autonomy: 80 },
  "GD-002": { id: "GD-002", name: "Graphic Composer", skillFile: "agents/GD-002_graphic_composer.md", team: 14, level: "sub", steps: ["moodboard", "production"] as any, gates: [], autonomy: 70 },
  "GD-003": { id: "GD-003", name: "Format Adapter", skillFile: "agents/GD-003_format_adapter.md", team: 14, level: "sub", steps: ["adaptation", "delivery"] as any, gates: [], autonomy: 85 },
  "GD-004": { id: "GD-004", name: "Motion Designer", skillFile: "agents/GD-004_motion_designer.md", team: 14, level: "sub", steps: ["production", "adaptation"] as any, gates: [], autonomy: 70 },
  "GD-005": { id: "GD-005", name: "Infographic Designer", skillFile: "agents/GD-005_infographic_designer.md", team: 14, level: "sub", steps: ["production"] as any, gates: [], autonomy: 75 },
  // ── Copywriter (cross-motor) ──
  "CW-001": { id: "CW-001", name: "Copywriter", skillFile: "agents/CW-001_copywriter.md", team: 15, level: "sub", steps: ["production"] as any, gates: [], autonomy: 75 },
  // ── Writers Room Motor ──
  "WR-L": { id: "WR-L", name: "Head Writer", skillFile: "agents/WR-L_head_writer.md", team: 16, level: "leader", steps: ["wr_brief", "wr_delivery"] as any, gates: ["wr-g1", "wr-g2"] as any, autonomy: 75 },
  "WR-001": { id: "WR-001", name: "Research Writer", skillFile: "agents/WR-001_research_writer.md", team: 16, level: "sub", steps: ["wr_research"] as any, gates: [], autonomy: 80 },
  "WR-002": { id: "WR-002", name: "AV Copywriter", skillFile: "agents/WR-002_av_copywriter.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 70 },
  "WR-003": { id: "WR-003", name: "Digital Copywriter", skillFile: "agents/WR-003_digital_copywriter.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 75 },
  "WR-004": { id: "WR-004", name: "SEO Content Writer", skillFile: "agents/WR-004_seo_content_writer.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 75 },
  "WR-005": { id: "WR-005", name: "Brand Copywriter", skillFile: "agents/WR-005_brand_copywriter.md", team: 16, level: "sub", steps: ["wr_draft", "wr_adaptation"] as any, gates: [], autonomy: 65 },
  // ── Audio Motor ──
  "AU-L": { id: "AU-L", name: "Sound Director", skillFile: "agents/AU-L_sound_director.md", team: 17, level: "leader", steps: ["au_brief", "au_delivery"] as any, gates: ["au-g1", "au-g2"] as any, autonomy: 75 },
  "AU-001": { id: "AU-001", name: "Sound Designer & SFX", skillFile: "agents/AU-001_sound_designer.md", team: 17, level: "sub", steps: ["au_sound_design"] as any, gates: [], autonomy: 75 },
  "AU-002": { id: "AU-002", name: "Music Producer", skillFile: "agents/AU-002_music_producer.md", team: 17, level: "sub", steps: ["au_production"] as any, gates: [], autonomy: 70 },
  "AU-003": { id: "AU-003", name: "Voice Director", skillFile: "agents/AU-003_voice_director.md", team: 17, level: "sub", steps: ["au_production"] as any, gates: [], autonomy: 70 },
  "AU-004": { id: "AU-004", name: "Mix Engineer", skillFile: "agents/AU-004_mix_engineer.md", team: 17, level: "sub", steps: ["au_mix_master"] as any, gates: [], autonomy: 80 },
  // ── Web Motor ──
  "WB-L": { id: "WB-L", name: "Web Director", skillFile: "agents/WB-L_web_director.md", team: 18, level: "leader", steps: ["wb_brief", "wb_delivery"] as any, gates: ["wb-g1", "wb-g2", "wb-g3"] as any, autonomy: 75 },
  "WB-001": { id: "WB-001", name: "Information Architect", skillFile: "agents/WB-001_information_architect.md", team: 18, level: "sub", steps: ["wb_architecture"] as any, gates: [], autonomy: 80 },
  "WB-002": { id: "WB-002", name: "Web Content Composer", skillFile: "agents/WB-002_web_content_composer.md", team: 18, level: "sub", steps: ["wb_content"] as any, gates: [], autonomy: 75 },
  "WB-003": { id: "WB-003", name: "SEO Specialist", skillFile: "agents/WB-003_seo_specialist.md", team: 18, level: "sub", steps: ["wb_seo"] as any, gates: [], autonomy: 80 },
  "WB-004": { id: "WB-004", name: "QA Tester", skillFile: "agents/WB-004_qa_tester.md", team: 18, level: "sub", steps: ["wb_qa"] as any, gates: [], autonomy: 85 },
  "WB-005": { id: "WB-005", name: "Build Engineer", skillFile: "agents/WB-005_build_engineer.md", team: 18, level: "sub", steps: ["wb_build"] as any, gates: [], autonomy: 80 },
  // ── Marketplace Motor (Transversal) ──
  "MK-L": { id: "MK-L", name: "Procurement Director", skillFile: "agents/MK-L_procurement_director.md", team: 19, level: "leader", steps: ["mk_request", "mk_delivery"] as any, gates: ["mk-g1", "mk-g2"] as any, autonomy: 70 },
  "MK-001": { id: "MK-001", name: "Vendor Scout", skillFile: "agents/MK-001_vendor_scout.md", team: 19, level: "sub", steps: ["mk_search", "mk_quote"] as any, gates: [], autonomy: 80 },
  "MK-002": { id: "MK-002", name: "Comparator", skillFile: "agents/MK-002_comparator.md", team: 19, level: "sub", steps: ["mk_compare"] as any, gates: [], autonomy: 85 },
  "MK-003": { id: "MK-003", name: "Contract Manager", skillFile: "agents/MK-003_contract_manager.md", team: 19, level: "sub", steps: ["mk_contract", "mk_tracking", "pp_production_tracking"] as any, gates: [], autonomy: 75 },
  // ── Print Production Motor ──
  "PP-L": { id: "PP-L", name: "Print Director", skillFile: "agents/PP-L_print_director.md", team: 20, level: "leader", steps: ["pp_brief", "pp_delivery"] as any, gates: ["pp-g1", "pp-g2"] as any, autonomy: 70 },
  "PP-001": { id: "PP-001", name: "Prepress Specialist", skillFile: "agents/PP-001_prepress_specialist.md", team: 20, level: "sub", steps: ["pp_prepress"] as any, gates: [], autonomy: 80 },
  "PP-002": { id: "PP-002", name: "Print Buyer", skillFile: "agents/PP-002_print_buyer.md", team: 20, level: "sub", steps: ["pp_vendor_request"] as any, gates: [], autonomy: 75 },
  "PP-003": { id: "PP-003", name: "Quality Inspector", skillFile: "agents/PP-003_quality_inspector.md", team: 20, level: "sub", steps: ["pp_quality_check"] as any, gates: [], autonomy: 70 },
  // ── Events Motor ──
  "EV-L": { id: "EV-L", name: "Event Director", skillFile: "agents/EV-L_event_director.md", team: 21, level: "leader", steps: ["ev_brief", "ev_concept", "ev_delivery"] as any, gates: ["ev-g1", "ev-g2", "ev-g3"] as any, autonomy: 70 },
  "EV-001": { id: "EV-001", name: "Event Planner", skillFile: "agents/EV-001_event_planner.md", team: 21, level: "sub", steps: ["ev_planning"] as any, gates: [], autonomy: 75 },
  "EV-002": { id: "EV-002", name: "Logistics Coordinator", skillFile: "agents/EV-002_logistics_coordinator.md", team: 21, level: "sub", steps: ["ev_vendor_setup"] as any, gates: [], autonomy: 70 },
  "EV-003": { id: "EV-003", name: "Content Activator", skillFile: "agents/EV-003_content_activator.md", team: 21, level: "sub", steps: ["ev_pre_event", "ev_live_event", "ev_post_event"] as any, gates: [], autonomy: 65 },
  "EV-004": { id: "EV-004", name: "Event Analyst", skillFile: "agents/EV-004_event_analyst.md", team: 21, level: "sub", steps: ["ev_post_event"] as any, gates: [], autonomy: 80 },
  "EV-005": { id: "EV-005", name: "Guest Manager", skillFile: "agents/EV-005_guest_manager.md", team: 21, level: "sub", steps: ["ev_pre_event", "ev_live_event"] as any, gates: [], autonomy: 75 },
  // ── Ads Motor ──
  "AD-L": { id: "AD-L", name: "Ads Director", skillFile: "agents/AD-L_ads_director.md", team: 22, level: "leader", steps: ["ad_brief", "ad_delivery"] as any, gates: ["ad-g1", "ad-g2"] as any, autonomy: 75 },
  "AD-001": { id: "AD-001", name: "Media Strategist", skillFile: "agents/AD-001_media_strategist.md", team: 22, level: "sub", steps: ["ad_strategy"] as any, gates: [], autonomy: 75 },
  "AD-002": { id: "AD-002", name: "Ad Production Coordinator", skillFile: "agents/AD-002_ad_production_coordinator.md", team: 22, level: "sub", steps: ["ad_creative"] as any, gates: [], autonomy: 70 },
  "AD-003": { id: "AD-003", name: "Targeting Specialist", skillFile: "agents/AD-003_targeting_specialist.md", team: 22, level: "sub", steps: ["ad_targeting"] as any, gates: [], autonomy: 75 },
  "AD-004": { id: "AD-004", name: "Campaign Assembler", skillFile: "agents/AD-004_campaign_assembler.md", team: 22, level: "sub", steps: ["ad_launch_kit"] as any, gates: [], autonomy: 80 },
  // ── Community Management Motor ──
  "CM-L": { id: "CM-L", name: "Community Director", skillFile: "agents/CM-L_community_director.md", team: 23, level: "leader", steps: ["cm_brief", "cm_delivery"] as any, gates: ["cm-g1", "cm-g2"] as any, autonomy: 75 },
  "CM-001": { id: "CM-001", name: "Calendar Planner", skillFile: "agents/CM-001_calendar_planner.md", team: 23, level: "sub", steps: ["cm_calendar"] as any, gates: [], autonomy: 75 },
  "CM-002": { id: "CM-002", name: "Social Coordinator", skillFile: "agents/CM-002_social_coordinator.md", team: 23, level: "sub", steps: ["cm_content_production", "cm_scheduling"] as any, gates: [], autonomy: 70 },
  "CM-003": { id: "CM-003", name: "Engagement Manager", skillFile: "agents/CM-003_engagement_manager.md", team: 23, level: "sub", steps: ["cm_monitoring"] as any, gates: [], autonomy: 65 },
  "CM-004": { id: "CM-004", name: "Social Analyst", skillFile: "agents/CM-004_social_analyst.md", team: 23, level: "sub", steps: ["cm_reporting"] as any, gates: [], autonomy: 80 },
  // ── Email Marketing Motor ──
  "EM-L": { id: "EM-L", name: "Email Director", skillFile: "agents/EM-L_email_director.md", team: 24, level: "leader", steps: ["em_brief", "em_delivery"] as any, gates: ["em-g1", "em-g2"] as any, autonomy: 75 },
  "EM-001": { id: "EM-001", name: "Sequence Designer", skillFile: "agents/EM-001_sequence_designer.md", team: 24, level: "sub", steps: ["em_strategy"] as any, gates: [], autonomy: 75 },
  "EM-002": { id: "EM-002", name: "Email Production Coordinator", skillFile: "agents/EM-002_email_production_coordinator.md", team: 24, level: "sub", steps: ["em_production", "em_send"] as any, gates: [], autonomy: 70 },
  "EM-003": { id: "EM-003", name: "Audience Segmenter", skillFile: "agents/EM-003_audience_segmenter.md", team: 24, level: "sub", steps: ["em_segmentation"] as any, gates: [], autonomy: 75 },
  "EM-004": { id: "EM-004", name: "Email Analyst", skillFile: "agents/EM-004_email_analyst.md", team: 24, level: "sub", steps: ["em_analysis"] as any, gates: [], autonomy: 80 },
  // ── SEO/Content Motor ──
  "SE-L": { id: "SE-L", name: "SEO Director", skillFile: "agents/SE-L_seo_director.md", team: 25, level: "leader", steps: ["se_brief", "se_delivery"] as any, gates: ["se-g1", "se-g2"] as any, autonomy: 75 },
  "SE-001": { id: "SE-001", name: "Technical Auditor", skillFile: "agents/SE-001_technical_auditor.md", team: 25, level: "sub", steps: ["se_audit"] as any, gates: [], autonomy: 80 },
  "SE-002": { id: "SE-002", name: "Keyword Strategist", skillFile: "agents/SE-002_keyword_strategist.md", team: 25, level: "sub", steps: ["se_keyword_strategy"] as any, gates: [], autonomy: 75 },
  "SE-003": { id: "SE-003", name: "Content Planner", skillFile: "agents/SE-003_content_planner.md", team: 25, level: "sub", steps: ["se_content_plan"] as any, gates: [], autonomy: 75 },
  "SE-004": { id: "SE-004", name: "Rankings Monitor", skillFile: "agents/SE-004_rankings_monitor.md", team: 25, level: "sub", steps: ["se_optimization", "se_reporting"] as any, gates: [], autonomy: 80 },
  // ── Channel Manager Motor ──
  "CH-L": { id: "CH-L", name: "Channel Director", skillFile: "agents/CH-L_channel_director.md", team: 26, level: "leader", steps: ["ch_request", "ch_delivery"] as any, gates: ["ch-g1"] as any, autonomy: 75 },
  "CH-001": { id: "CH-001", name: "Digital Channel Specialist", skillFile: "agents/CH-001_digital_channel_specialist.md", team: 26, level: "sub", steps: ["ch_analysis"] as any, gates: [], autonomy: 80 },
  "CH-002": { id: "CH-002", name: "Traditional Channel Specialist", skillFile: "agents/CH-002_traditional_channel_specialist.md", team: 26, level: "sub", steps: ["ch_analysis"] as any, gates: [], autonomy: 75 },
  "CH-003": { id: "CH-003", name: "Specs Engineer", skillFile: "agents/CH-003_specs_engineer.md", team: 26, level: "sub", steps: ["ch_specs"] as any, gates: [], autonomy: 85 },
  // ── Opportunity Agent (loop, not pipeline) ──
  "OP-L": { id: "OP-L", name: "Opportunity Director", skillFile: "agents/OP-L_opportunity_director.md", team: 27, level: "leader", steps: [], gates: [], autonomy: 70 },
  "OP-001": { id: "OP-001", name: "Signal Scanner", skillFile: "agents/OP-001_signal_scanner.md", team: 27, level: "sub", steps: [], gates: [], autonomy: 80 },
  "OP-002": { id: "OP-002", name: "Activation Planner", skillFile: "agents/OP-002_activation_planner.md", team: 27, level: "sub", steps: [], gates: [], autonomy: 75 },
  // ── Intelligence Engine Agents ──
  "BL-L": {
    id: "BL-L",
    name: "Brand Intelligence Lead",
    skillFile: "agents/BL-L_brand_intelligence_lead.md",
    team: 12,
    level: "leader",
    steps: ["analyze", "report"] as any,
    gates: [],
    autonomy: 75,
  },
  "BL-001": {
    id: "BL-001",
    name: "Mention Scanner",
    skillFile: "agents/BL-001_mention_scanner.md",
    team: 12,
    level: "sub",
    steps: ["collect"] as any,
    gates: [],
    autonomy: 90,
  },
  "BL-002": {
    id: "BL-002",
    name: "Sentiment Analyst",
    skillFile: "agents/BL-002_sentiment_analyst.md",
    team: 12,
    level: "sub",
    steps: ["analyze"] as any,
    gates: [],
    autonomy: 85,
  },
  "CL-L": {
    id: "CL-L",
    name: "Culture Intelligence Lead",
    skillFile: "agents/CL-L_culture_intelligence_lead.md",
    team: 12,
    level: "leader",
    steps: ["analyze", "report"] as any,
    gates: [],
    autonomy: 75,
  },
  "CL-001": {
    id: "CL-001",
    name: "Trend Scanner",
    skillFile: "agents/CL-001_trend_scanner.md",
    team: 12,
    level: "sub",
    steps: ["collect"] as any,
    gates: [],
    autonomy: 90,
  },
  "CL-002": {
    id: "CL-002",
    name: "Relevance Analyst",
    skillFile: "agents/CL-002_relevance_analyst.md",
    team: 12,
    level: "sub",
    steps: ["analyze"] as any,
    gates: [],
    autonomy: 85,
  },
  "IL-L": {
    id: "IL-L",
    name: "Industry Intelligence Lead",
    skillFile: "agents/IL-L_industry_intelligence_lead.md",
    team: 12,
    level: "leader",
    steps: ["analyze", "report"] as any,
    gates: [],
    autonomy: 75,
  },
  "IL-001": {
    id: "IL-001",
    name: "Research Scanner",
    skillFile: "agents/IL-001_research_scanner.md",
    team: 12,
    level: "sub",
    steps: ["collect"] as any,
    gates: [],
    autonomy: 90,
  },
  "IL-002": {
    id: "IL-002",
    name: "Trend Analyst",
    skillFile: "agents/IL-002_trend_analyst.md",
    team: 12,
    level: "sub",
    steps: ["analyze"] as any,
    gates: [],
    autonomy: 85,
  },
  "CO-L": {
    id: "CO-L",
    name: "Competitive Intelligence Lead",
    skillFile: "agents/CO-L_competitive_intelligence_lead.md",
    team: 12,
    level: "leader",
    steps: ["analyze", "report"] as any,
    gates: [],
    autonomy: 75,
  },
  "CO-001": {
    id: "CO-001",
    name: "Competitor Scanner",
    skillFile: "agents/CO-001_competitor_scanner.md",
    team: 12,
    level: "sub",
    steps: ["collect"] as any,
    gates: [],
    autonomy: 90,
  },
  "CO-002": {
    id: "CO-002",
    name: "Gap Analyst",
    skillFile: "agents/CO-002_gap_analyst.md",
    team: 12,
    level: "sub",
    steps: ["analyze"] as any,
    gates: [],
    autonomy: 85,
  },
  "OA-L": {
    id: "OA-L",
    name: "Opportunity Director",
    skillFile: "agents/OA-L_opportunity_director.md",
    team: 12,
    level: "leader",
    steps: ["evaluate", "prioritize"] as any,
    gates: [],
    autonomy: 70,
  },
  "OA-001": {
    id: "OA-001",
    name: "Opportunity Scanner",
    skillFile: "agents/OA-001_opportunity_scanner.md",
    team: 12,
    level: "sub",
    steps: ["aggregate"] as any,
    gates: [],
    autonomy: 85,
  },
  "OA-002": {
    id: "OA-002",
    name: "Brief Generator",
    skillFile: "agents/OA-002_brief_generator.md",
    team: 12,
    level: "sub",
    steps: ["generate"] as any,
    gates: [],
    autonomy: 80,
  },
  // ── Sales/CRM Motor ──
  "SL-L": { id: "SL-L", name: "Sales Director", skillFile: "agents/SL-L_sales_director.md", team: 32, level: "leader", steps: ["sl_capture", "sl_negotiate", "sl_close", "sl_delivery"] as any, gates: ["sl-g1", "sl-g2"] as any, autonomy: 70 },
  "SL-001": { id: "SL-001", name: "Lead Capture Agent", skillFile: "agents/SL-001_lead_capture_agent.md", team: 32, level: "sub", steps: ["sl_capture"] as any, gates: [], autonomy: 85 },
  "SL-002": { id: "SL-002", name: "Lead Enricher", skillFile: "agents/SL-002_lead_enricher.md", team: 32, level: "sub", steps: ["sl_enrich"] as any, gates: [], autonomy: 80 },
  "SL-003": { id: "SL-003", name: "Lead Scorer", skillFile: "agents/SL-003_lead_scorer.md", team: 32, level: "sub", steps: ["sl_score"] as any, gates: [], autonomy: 80 },
  "SL-004": { id: "SL-004", name: "Nurture Coordinator", skillFile: "agents/SL-004_nurture_coordinator.md", team: 32, level: "sub", steps: ["sl_nurture"] as any, gates: [], autonomy: 75 },
  "SL-005": { id: "SL-005", name: "Proposal Generator", skillFile: "agents/SL-005_proposal_generator.md", team: 32, level: "sub", steps: ["sl_proposal"] as any, gates: [], autonomy: 65 },
  "SL-006": { id: "SL-006", name: "Attribution Analyst", skillFile: "agents/SL-006_attribution_analyst.md", team: 32, level: "sub", steps: ["sl_attribution"] as any, gates: [], autonomy: 80 },
  // ── Analytics Motor ──
  "AN-L": { id: "AN-L", name: "Analytics Director", skillFile: "agents/AN-L_analytics_director.md", team: 33, level: "leader", steps: ["an_request", "an_deliver"] as any, gates: ["an-g1"] as any, autonomy: 75 },
  "AN-001": { id: "AN-001", name: "Data Collector", skillFile: "agents/AN-001_data_collector.md", team: 33, level: "sub", steps: ["an_collect"] as any, gates: [], autonomy: 85 },
  "AN-002": { id: "AN-002", name: "Metrics Analyst", skillFile: "agents/AN-002_metrics_analyst.md", team: 33, level: "sub", steps: ["an_analyze"] as any, gates: [], autonomy: 80 },
  "AN-003": { id: "AN-003", name: "Dashboard Builder", skillFile: "agents/AN-003_dashboard_builder.md", team: 33, level: "sub", steps: ["an_visualize"] as any, gates: [], autonomy: 80 },
  "AN-004": { id: "AN-004", name: "Report Generator", skillFile: "agents/AN-004_report_generator.md", team: 33, level: "sub", steps: ["an_visualize"] as any, gates: [], autonomy: 80 },
  "AN-005": { id: "AN-005", name: "NL Query Agent", skillFile: "agents/AN-005_nl_query_agent.md", team: 33, level: "sub", steps: ["an_analyze"] as any, gates: [], autonomy: 75 },
  "AN-006": { id: "AN-006", name: "Insight Detector", skillFile: "agents/AN-006_insight_detector.md", team: 33, level: "sub", steps: ["an_detect"] as any, gates: [], autonomy: 85 },
  // ── Budget Engine (Team 36) ──
  "BU-L": { id: "BU-L", name: "Budget Director", skillFile: "agents/BU-L_budget_director.md", team: 36, level: "leader", steps: ["bu_allocation", "bu_roi_calculation"] as any, gates: ["bu-g1"] as any, autonomy: 70 },
  "BU-001": { id: "BU-001", name: "Budget Allocator", skillFile: "agents/BU-001_budget_allocator.md", team: 36, level: "sub", steps: ["bu_allocation"] as any, gates: [], autonomy: 80 },
  "BU-002": { id: "BU-002", name: "Spend Monitor", skillFile: "agents/BU-002_spend_monitor.md", team: 36, level: "sub", steps: ["bu_spend_tracking"] as any, gates: [], autonomy: 90 },
  "BU-003": { id: "BU-003", name: "Vendor Analyst", skillFile: "agents/BU-003_vendor_analyst.md", team: 36, level: "sub", steps: ["bu_vendor_validation"] as any, gates: [], autonomy: 85 },
  "BU-004": { id: "BU-004", name: "ROI Analyst", skillFile: "agents/BU-004_roi_analyst.md", team: 36, level: "sub", steps: ["bu_roi_calculation"] as any, gates: [], autonomy: 85 },
  // ── Scale Engine (team 37) ──
  "SK-L": { id: "SK-L", name: "Campaign Orchestrator", skillFile: "agents/SK-L_campaign_orchestrator.md", team: 37, level: "leader", steps: ["sk_decompose", "sk_dispatch", "sk_consolidate"] as any, gates: ["sk-g1"] as any, autonomy: 70 },
  "SK-001": { id: "SK-001", name: "Brief Decomposer", skillFile: "agents/SK-001_brief_decomposer.md", team: 37, level: "sub", steps: ["sk_decompose"] as any, gates: [], autonomy: 85 },
  "SK-002": { id: "SK-002", name: "Progress Monitor", skillFile: "agents/SK-002_progress_monitor.md", team: 37, level: "sub", steps: ["sk_monitor"] as any, gates: [], autonomy: 90 },
  "SK-003": { id: "SK-003", name: "Asset Curator", skillFile: "agents/SK-003_asset_curator.md", team: 37, level: "sub", steps: ["sk_dispatch"] as any, gates: [], autonomy: 90 },
  // ── Financial Motor (evolves XA-001) ──
  "FN-L": { id: "FN-L", name: "Financial Director", skillFile: "agents/FN-L_financial_director.md", team: 34, level: "leader", steps: ["fn_request", "fn_deliver"] as any, gates: ["fn-g1"] as any, autonomy: 75 },
  "FN-001": { id: "FN-001", name: "Budget Allocator", skillFile: "agents/FN-001_budget_allocator.md", team: 34, level: "sub", steps: ["fn_budget"] as any, gates: [], autonomy: 80 },
  "FN-002": { id: "FN-002", name: "Spend Tracker", skillFile: "agents/FN-002_spend_tracker.md", team: 34, level: "sub", steps: ["fn_tracking"] as any, gates: [], autonomy: 85 },
  "FN-003": { id: "FN-003", name: "P&L Analyst", skillFile: "agents/FN-003_pl_analyst.md", team: 34, level: "sub", steps: ["fn_pl"] as any, gates: [], autonomy: 80 },
  // ── Security Team ──
  "SC-L": { id: "SC-L", name: "Security Architect", skillFile: "agents/SC-L_security_architect.md", team: 35, level: "leader", steps: ["sec_audit", "sec_report", "sec_deliver"] as any, gates: ["sec-g1"] as any, autonomy: 70 },
  "SC-001": { id: "SC-001", name: "Code Guardian", skillFile: "agents/SC-001_code_guardian.md", team: 35, level: "sub", steps: ["sec_scan", "sec_remediate"] as any, gates: [], autonomy: 80 },
  "SC-002": { id: "SC-002", name: "Data Protection Officer", skillFile: "agents/SC-002_data_protection_officer.md", team: 35, level: "sub", steps: ["sec_scan"] as any, gates: [], autonomy: 75 },
  "SC-003": { id: "SC-003", name: "Agent Auditor", skillFile: "agents/SC-003_agent_auditor.md", team: 35, level: "sub", steps: ["sec_scan"] as any, gates: [], autonomy: 80 },
  "SC-004": { id: "SC-004", name: "Threat Hunter", skillFile: "agents/SC-004_threat_hunter.md", team: 35, level: "sub", steps: ["sec_scan"] as any, gates: [], autonomy: 85 },
  "SC-005": { id: "SC-005", name: "Infrastructure Sentinel", skillFile: "agents/SC-005_infrastructure_sentinel.md", team: 35, level: "sub", steps: ["sec_scan", "sec_remediate"] as any, gates: [], autonomy: 95 },
  "PO-L": {
    id: "PO-L",
    name: "Positioning Strategist",
    skillFile: "agents/PO-L_positioning_strategist.md",
    team: 16,
    level: "leader",
    steps: ["po_gap_analysis", "po_positioning_definition", "po_target_definition", "po_transition_plan"],
    gates: ["po-g1", "po-g2"],
    autonomy: 70,
  },
  "PO-001": {
    id: "PO-001",
    name: "Perception Auditor",
    skillFile: "agents/PO-001_perception_auditor.md",
    team: 16,
    level: "sub",
    steps: ["po_perception_audit", "po_current_audit"],
    gates: [],
    autonomy: 85,
  },
  "PO-002": {
    id: "PO-002",
    name: "Competitive Mapper",
    skillFile: "agents/PO-002_competitive_mapper.md",
    team: 16,
    level: "sub",
    steps: ["po_positioning_definition"],
    gates: [],
    autonomy: 85,
  },
  "PO-003": {
    id: "PO-003",
    name: "Transition Architect",
    skillFile: "agents/PO-003_transition_architect.md",
    team: 16,
    level: "sub",
    steps: ["po_phase_design", "po_execution_monitoring"],
    gates: [],
    autonomy: 80,
  },
};
