import type { AgentRegistryEntry } from "../shared/types.js";

export const AGENT_REGISTRY: Record<string, AgentRegistryEntry> = {
  "TL-001": {
    id: "TL-001",
    name: "Project Manager",
    skillFile: "agents/TL-001_project_manager.md",
    team: 0,
    level: "top",
    steps: [],
    gates: [],
    autonomy: 90,
  },
  "TL-002": {
    id: "TL-002",
    name: "Showrunner",
    skillFile: "agents/TL-002_showrunner.md",
    team: 0,
    level: "top",
    steps: [],
    gates: ["g1", "g2", "g3", "g4", "g5"],
    autonomy: 90,
  },
  "TL-003": {
    id: "TL-003",
    name: "Producer",
    skillFile: "agents/TL-003_producer.md",
    team: 0,
    level: "top",
    steps: ["visual_look"],
    gates: [],
    autonomy: 85,
  },
  "T1-L": {
    id: "T1-L",
    name: "Creative Director",
    skillFile: "agents/T1-L_creative_director.md",
    team: 1,
    level: "leader",
    steps: ["brief", "concept"],
    gates: ["g2"],
    autonomy: 85,
  },
  "T2-L": {
    id: "T2-L",
    name: "Head Writer",
    skillFile: "agents/T2-L_head_writer.md",
    team: 2,
    level: "leader",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T2-002": {
    id: "T2-002",
    name: "AV Copywriter",
    skillFile: "agents/T2-002_av_copywriter.md",
    team: 2,
    level: "sub",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T2-006": {
    id: "T2-006",
    name: "Script Doctor",
    skillFile: "agents/T2-006_script_doctor.md",
    team: 2,
    level: "sub",
    steps: ["script"],
    gates: [],
    autonomy: 80,
  },
  "T3-L": {
    id: "T3-L",
    name: "Director of Photography",
    skillFile: "agents/T3-L_director_of_photography.md",
    team: 3,
    level: "leader",
    steps: ["visual_look", "storyboard"],
    gates: [],
    autonomy: 75,
  },
  "T3-003": {
    id: "T3-003",
    name: "Cinematic Prompt Engineer",
    skillFile: "agents/T3-003_cinematic_prompt_engineer.md",
    team: 3,
    level: "sub",
    steps: ["storyboard", "video_gen"],
    gates: [],
    autonomy: 75,
  },
  "T5-L": {
    id: "T5-L",
    name: "Sonorizador",
    skillFile: "agents/T5-L_sonorizador.md",
    team: 5,
    level: "leader",
    steps: ["audio"],
    gates: [],
    autonomy: 70,
  },
  "T6-L": {
    id: "T6-L",
    name: "Editor",
    skillFile: "agents/T6-L_editor.md",
    team: 6,
    level: "leader",
    steps: ["edit", "polish"],
    gates: [],
    autonomy: 65,
  },
  "T6-003": {
    id: "T6-003",
    name: "Delivery Master",
    skillFile: "agents/T6-003_delivery_master.md",
    team: 6,
    level: "sub",
    steps: ["delivery"],
    gates: [],
    autonomy: 90,
  },
  "T7-L": {
    id: "T7-L",
    name: "Client Service",
    skillFile: "agents/T7-L_client_service.md",
    team: 7,
    level: "leader",
    steps: ["brief", "delivery"],
    gates: [],
    autonomy: 85,
  },
  "XF-001": {
    id: "XF-001",
    name: "Cinematographic Critic",
    skillFile: "agents/XF-001_cinematographic_critic.md",
    team: 0,
    level: "cross_functional",
    steps: [],
    gates: ["g4", "g5"],
    autonomy: 100,
  },
  "T9-L": {
    id: "T9-L",
    name: "AI Model Director",
    skillFile: "agents/T9-L_ai_model_director.md",
    team: 9,
    level: "leader",
    steps: ["model_config"],
    gates: [],
    autonomy: 80,
  },
  "T9-001": {
    id: "T9-001",
    name: "Text Model Specialist",
    skillFile: "agents/T9-001_text_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-002": {
    id: "T9-002",
    name: "Image Model Specialist",
    skillFile: "agents/T9-002_image_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-003": {
    id: "T9-003",
    name: "Video Model Specialist",
    skillFile: "agents/T9-003_video_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-004": {
    id: "T9-004",
    name: "Audio Model Specialist",
    skillFile: "agents/T9-004_audio_model_specialist.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
  "T9-005": {
    id: "T9-005",
    name: "Model Benchmarker",
    skillFile: "agents/T9-005_model_benchmarker.md",
    team: 9,
    level: "sub",
    steps: [],
    gates: [],
    autonomy: 80,
  },
};
